name: thesis
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - affine=2.3.0
  - alabaster=1.0.0
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - branca=0.6.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - cfitsio=3.470
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.21.2
  - executing=0.8.3
  - expat=2.6.4
  - fiona=1.10.1
  - folium=0.19.6
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.6.2
  - geos=3.10.6
  - geotiff=1.7.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - h11=0.14.0
  - h5py=3.12.1
  - hdf4=4.2.13
  - hdf5=1.14.5
  - httpcore=1.0.2
  - httpx=0.27.0

  - idna=3.7
  - imagesize=1.4.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - kealib=1.5.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libboost=1.82.0
  - libcurl=8.12.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libgdal=3.6.2
  - libglib=2.78.4
  - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libpng=1.6.39
  - libpq=17.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzip=1.8.0
  - libzlib=1.2.13
  - line_profiler=4.2.0
  - llvm=18.1.7
  - lz4-c=1.9.4
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - maturin=1.7.8
  - minizip=4.0.3
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.3.2
  - notebook-shim=0.2.3
  - numexpr=2.10.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.2
  - openssl=3.5.0
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.40.0
  - platformdirs=3.10.0
  - poppler=24.09.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - rasterio=1.4.3
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - roman-numerals-py=3.1.0
  - rpds-py=0.22.3
  - rtree=1.0.1
  - rust=1.82.0
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - send2trash=1.8.2
  - setuptools=73.0.1
  - shapely=2.0.6
  - six=1.16.0
  - sniffio=1.3.0
  - snowballstemmer=3.0.1
  - snuggs=1.4.7
  - soupsieve=2.5
  - sphinx=8.2.3
  - sphinx-autodoc-typehints=3.2.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tinycss2=1.4.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - arrow==1.3.0
      - blinker==1.9.0
      - configargparse==1.7
      - cupy-cuda12x==13.3.0
      - cython==3.1.0b1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - ezdxf==1.4.0
      - fastrlock==0.8.3
      - flask==3.0.3
      - fqdn==1.5.1
      - furo==2024.8.6
      - geopandas==1.0.1
      - importlib-metadata==8.6.1
      - iniconfig==2.1.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jsonpointer==3.0.0
      - jupyterlab-widgets==3.0.13
      - laspy==2.5.4
      - lazrs==0.6.2
      - mapbox-vector-tile==2.1.0
      - narwhals==1.30.0
      - open3d==0.19.0
      - plotly==6.0.0
      - pluggy==1.6.0
      - protobuf==5.29.3
      - pyclipper==1.3.0.post6
      - pyogrio==0.10.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pytest==8.3.5
      - retrying==1.3.4
      - rusterizer-3d==0.1.1
      - snakeviz==2.2.2
      - sphinx-basic-ng==1.0.0b2
      - startinpy==0.12.1
      - toml==0.10.2
      - trimesh==4.6.4
      - types-python-dateutil==2.9.0.20241206
      - uri-template==1.3.0
      - webcolors==24.11.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - zipp==3.21.0
